### ISSUE TITLE
Please add copyright notice

### ISSUE THREAD

**Issue by BudickDa** [SwiftBlue/google-nlp#1]
I noticed you forked my repository. To be in conformity with the MIT license, I have to ask you to add my name to the copyright notice. 
Thank you for contributing to open source.

Cheers
Daniel

**Comment by BudickDa** [comment]
After you not reacting, I took another look and found, that you forked my repository here: 
https://github.com/dberube/google-nlp-api
and just copy and pasted the code in the first commit: https://github.com/SwiftBlue/google-nlp/commit/197a1f1c1a5e76a29f5401b8281e7630c1e34044

This is highly unethical and a copyright infringement. This is not how open source is supposed to work, I issued a DCMA takedown.

**Comment by dberube** [comment]
Hi @BudickDa. First, let me thank you for providing the inspiration and blueprint for this project.  It was written from scratch, but your repo was certainly the inspiration for this and used the structure as a blueprint for this project.

As such, your name has been added to the Copyright in the license in release [v0.5.3](https://github.com/SwiftBlue/google-nlp/releases/tag/v0.5.3) in commit [f94237a](https://github.com/SwiftBlue/google-nlp/commit/f94237ad4e96c7ab45afd94277846c1cdac8558d).

Thank you again for the work you've put in!
